insert into public.physicists (
  name,
  university_origin,
  current_city,
  country,
  current_institution,
  position,
  research_field,
  email,
  show_email,
  website,
  orcid,
  linkedin,
  year_left_university,
  latitude,
  longitude,
  edit_code_hash,
  is_approved,
  is_public,
  consent_given
) values
(
  'Dr. Elena Varga',
  'Department of Physics',
  'Geneva',
  'Switzerland',
  'CERN',
  'Research Fellow',
  'Particle Physics',
  'elena.varga@example.edu',
  false,
  'https://example.edu/elena-varga',
  '0000-0002-1825-0097',
  null,
  2018,
  46.2044,
  6.1432,
  '$2a$12$7EqJtq98hPqEX7fNZaFWoOa8I84PuQdxTn0.xpdhJ28g0nQL7OZ4e',
  true,
  true,
  true
),
(
  'Prof. Marcus Lee',
  'Institute for Theoretical Physics',
  'Cambridge',
  'United Kingdom',
  'University of Cambridge',
  'Professor',
  'Quantum Field Theory',
  null,
  false,
  'https://example.edu/marcus-lee',
  null,
  'https://www.linkedin.com/in/example-marcus-lee',
  2010,
  52.2053,
  0.1218,
  '$2a$12$7EqJtq98hPqEX7fNZaFWoOa8I84PuQdxTn0.xpdhJ28g0nQL7OZ4e',
  true,
  true,
  true
),
(
  'Dr. Sofia Mendes',
  'Astronomy and Astrophysics Group',
  'Santiago',
  'Chile',
  'European Southern Observatory',
  'Staff Scientist',
  'Astrophysics',
  'sofia.mendes@example.edu',
  true,
  null,
  '0000-0003-1415-9265',
  null,
  2016,
  -33.4489,
  -70.6693,
  '$2a$12$7EqJtq98hPqEX7fNZaFWoOa8I84PuQdxTn0.xpdhJ28g0nQL7OZ4e',
  true,
  true,
  true
),
(
  'Dr. Anika Rao',
  'Condensed Matter Physics',
  'Bangalore',
  'India',
  'Indian Institute of Science',
  'Assistant Professor',
  'Condensed Matter',
  null,
  false,
  'https://example.edu/anika-rao',
  null,
  null,
  2020,
  12.9716,
  77.5946,
  '$2a$12$7EqJtq98hPqEX7fNZaFWoOa8I84PuQdxTn0.xpdhJ28g0nQL7OZ4e',
  true,
  true,
  true
),
(
  'Dr. Noah Stein',
  'Laser Physics Laboratory',
  'Berkeley',
  'United States',
  'Lawrence Berkeley National Laboratory',
  'Postdoctoral Researcher',
  'Atomic, Molecular, and Optical Physics',
  'noah.stein@example.edu',
  false,
  null,
  null,
  'https://www.linkedin.com/in/example-noah-stein',
  2022,
  37.8715,
  -122.2730,
  '$2a$12$7EqJtq98hPqEX7fNZaFWoOa8I84PuQdxTn0.xpdhJ28g0nQL7OZ4e',
  true,
  true,
  true
);
